[project]
name = "watchmen-metricflow"
version = "18.0.1"
description = ""
authors = [
    {name = "luke0623",email = "luke0623@outlook.com"}
]
license = "MIT"
packages = [
    { include = "watchmen_metricflow", from = "src" }
]


[tool.poetry.dependencies]
python = "~3.12"
passlib = "^1.7.4"
bcrypt = "^4.2.0"
python-multipart = "^0.0.9"
dbt-metricflow = ">=0.8.2,<0.9.0"
dbt-postgres = ">=1.8.0,<2.0.0"
fastapi-mcp = ">=0.4.0,<0.5.0"
watchmen-lineage = "18.0.1"
watchmen-model = "18.0.1"
watchmen-meta = "18.0.1"
watchmen-rest = "18.0.1"
watchmen-data-surface = "18.0.1"
watchmen-inquiry-surface = "18.0.1"
watchmen-indicator-surface = "18.0.1"
watchmen-storage-mysql = { version = "18.0.1", optional = true }
watchmen-storage-oracle = { version = "18.0.1", optional = true }
watchmen-storage-mssql = { version = "18.0.1", optional = true }
watchmen-storage-postgresql = { version = "18.0.1", optional = true }


[tool.poetry.group.dev.dependencies]

[tool.poetry.extras]
trino = ["watchmen-inquiry-trino"]
mysql = ["watchmen-storage-mysql", "cryptography"]
oracle = ["watchmen-storage-oracle"]
mongodb = ["watchmen-storage-mongodb"]
mssql = ["watchmen-storage-mssql"]
postgresql = ["watchmen-storage-postgresql"]
oss = ["watchmen-storage-oss"]
s3 = ["watchmen-storage-s3"]
adls = ["watchmen-storage-adls"]
collector = ["watchmen-collector-surface"]
kafka = ["kafka-python", "aiokafka"]
rabbit = ["aio-pika"]
prometheus = ["starlette-prometheus"]
standard_ext_writer = ["requests"]
es_ext_writer = []
sso = ["python3-saml", "cryptography"]
boto3 = ["boto3"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
