[project]
name = "watchmen-metricflow"
version = "17.0.0"
description = ""
authors = [
    {name = "luke0623",email = "luke0623@outlook.com"}
]
license = "MIT"
packages = [
    { include = "watchmen_metricflow", from = "src" }
]


[tool.poetry.dependencies]
python = "~3.12"
passlib = "^1.7.4"
bcrypt = "^4.2.0"
python-multipart = "^0.0.9"
dbt-metricflow = ">=0.8.2,<0.9.0"
dbt-postgres = ">=1.8.0,<2.0.0"
uvicorn = ">=0.30.1,<0.31.0"
fastapi = ">=0.116.1,<0.117.0"
uvloop = ">=0.21.0,<0.22.0"
pydantic-settings = ">=2.10.1,<3.0.0"
python-json-logger = ">=3.3.0,<4.0.0"
sqlalchemy = ">=2.0.43,<3.0.0"
pymysql = ">=1.1.2,<2.0.0"
python-jose = ">=3.5.0,<4.0.0"
cacheout = ">=0.16.0,<0.17.0"
dask = ">=2025.7.0,<2026.0.0"
distributed = ">=2025.7.0,<2026.0.0"
apscheduler = ">=3.11.0,<4.0.0"
pycryptodome = ">=2.3.4,<4.0.0"
fastapi-mcp = ">=0.4.0,<0.5.0"
numpy = ">=2.3.4,<3.0.0"
watchmen-lineage = { path = "../watchmen-lineage", develop = true }
watchmen-model = { path = "../watchmen-model", develop = true }
watchmen-meta = { path = "../watchmen-meta", develop = true }
watchmen-rest = { path = "../watchmen-rest", develop = true }
watchmen-data-surface = { path = "../watchmen-data-surface", develop = true }
watchmen-inquiry-surface = { path = "../watchmen-inquiry-surface", develop = true }
watchmen-indicator-surface = { path = "../watchmen-indicator-surface", develop = true }
watchmen-storage-mysql = { path = "../watchmen-storage-mysql", develop = true, optional = true }
watchmen-storage-oracle = { path = "../watchmen-storage-oracle", develop = true, optional = true }
watchmen-storage-mssql = { path = "../watchmen-storage-mssql", develop = true, optional = true }
watchmen-storage-postgresql = { path = "../watchmen-storage-postgresql", develop = true, optional = true }


[tool.poetry.group.dev.dependencies]

[tool.poetry.extras]
trino = ["watchmen-inquiry-trino"]
mysql = ["watchmen-storage-mysql", "cryptography"]
oracle = ["watchmen-storage-oracle"]
mongodb = ["watchmen-storage-mongodb"]
mssql = ["watchmen-storage-mssql"]
postgresql = ["watchmen-storage-postgresql"]
oss = ["watchmen-storage-oss"]
s3 = ["watchmen-storage-s3"]
adls = ["watchmen-storage-adls"]
collector = ["watchmen-collector-surface"]
kafka = ["kafka-python", "aiokafka"]
rabbit = ["aio-pika"]
prometheus = ["starlette-prometheus"]
standard_ext_writer = ["requests"]
es_ext_writer = []
sso = ["python3-saml", "cryptography"]
boto3 = ["boto3"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
