[tool.poetry]
name = "watchmen-storage-rds"
version = "18.0.1"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage_rds", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
SQLAlchemy = "~2.0.35"
watchmen-storage = "18.0.1"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
