[tool.poetry]
name = "watchmen-storage"
version = "16.1.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.24.45"
watchmen-model = { path = "../watchmen-model", develop = true }


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
