[tool.poetry]
name = "watchmen-storage"
version = "16.5.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = {version = "^1.24.20", optional = true }
watchmen-model = "16.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
