[tool.poetry]
name = "watchmen-cli"
version = "17.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_cli", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
fire = "^0.6.0"
requests = "^2.32.3"
watchmen-utilities = "17.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "foo"
url = "https://pypi.org/simple/"
default = true