[tool.poetry]
name = "watchmen-inquiry-kernel"
version = "17.0.1"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_inquiry_kernel", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
watchmen-data-kernel = "17.0.1"
watchmen-pipeline-kernel = "17.0.1"
watchmen-inquiry-trino = { version = "17.0.1", optional = true }
watchmen-storage-mysql = { version = "17.0.1", optional = true }
watchmen-storage-oracle = { version = "17.0.1", optional = true }
watchmen-storage-mongodb = { version = "17.0.1", optional = true }
watchmen-storage-mssql = { version = "17.0.1", optional = true }
watchmen-storage-postgresql = { version = "17.0.1", optional = true }
watchmen-storage-oss = { version = "17.0.1", optional = true }
watchmen-storage-s3 = { version = "17.0.1", optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
mysql = ["watchmen-storage-mysql"]
oracle = ["watchmen-storage-oracle"]
mongodb = ["watchmen-storage-mongodb"]
mssql = ["watchmen-storage-mssql"]
postgresql = ["watchmen-storage-postgresql"]
trino = ["watchmen-inquiry-trino"]
oss = ["watchmen-storage-oss"]
s3 = ["watchmen-storage-s3"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
