[tool.poetry]
name = "watchmen-utilities"
version = "16.4.10"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_utilities", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.9.0"
python-json-logger = "^2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
