[tool.poetry]
name = "watchmen-function-azure"
version = "17.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_function", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
azure-functions = "^1.11.2"
watchmen-pipeline-surface = "17.0.0"
watchmen-storage-mysql = "17.0.0"



[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
