[tool.poetry]
name = "watchmen-storage-oracle"
version = "16.0.38"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage_oracle", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
SQLAlchemy = "^1.4.31"
cx-Oracle = "^8.3.0"
watchmen-storage = "16.0.38"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
