[tool.poetry]
name = "watchmen-inquiry-trino"
version = "17.0.2"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_inquiry_trino", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
trino = "^0.329.0"
watchmen-data-kernel = "17.0.2"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
