[tool.poetry]
name = "watchmen-storage-mysql"
version = "17.0.1"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage_mysql", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
PyMySQL = "^1.1.1"
cryptography = "^42.0.8"
watchmen-storage-rds = "17.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
