[tool.poetry]
name = "watchmen-storage-oss"
version = "18.0.1"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage_oss", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
oss2 = "2.18.6"
watchmen-storage = "18.0.1"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
