[tool.poetry]
name = "watchmen-storage-postgresql"
version = "16.4.10"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage_postgresql", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
psycopg2-binary = "^2.9.3"
watchmen-storage-rds = "16.4.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
