[tool.poetry]
name = "watchmen-model"
version = "18.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_model", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
pydantic = "^2.9.0b2"
pydantic-settings = "^2.4.0"
watchmen-utilities = { path = "../watchmen-utilities", develop = true }
sqlparse = "^0.5.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
