[tool.poetry]
name = "watchmen-storage-s3"
version = "17.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_storage_s3", from = "src" }
]

[tool.poetry.dependencies]
python = "~3.12"
boto3 = "^1.34.140"
watchmen-storage = "17.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
